server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ./mnt/var/positions-docker.yaml

# Where to send logs.
clients:
- url: http://loki:3100/loki/api/v1/push
  external_labels:
    host: docker

# What to read.
scrape_configs:
- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

- job_name: containers_new
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 15s
      filters:
        - name: label
          values: ["org.label-schema.name=validator"]

  pipeline_stages:
    - docker: {}
    - static_labels:
        job: "promtail"
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'