[package]
name = "FastX"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/diem/diem.git", subdir="language/move-stdlib", rev = "56ab033cc403b489e891424a629e76f643d4fb6b" }

[addresses]
Std = "0x1"
FastX = "0x2"
Examples = "0x3"

[dev-addresses]
Std = "0x1"
FastX = "0x2"
Examples = "0x3"
