[package]
name = "fastx-framework"
version = "0.1.0"
edition = "2018"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for fastX platform"
license = "Apache-2.0"
publish = false

[dependencies]
smallvec = "1.6.1"

## uncomment for debugging with local copy of diem repo
# move-binary-format = { path = "../../../diem/language/move-binary-format" }
# move-core-types = { path = "../../../diem/language/move-core/types" }
# move-lang = { path = "../../../diem/language/move-lang" }
# move-package = { path = "../../../diem/language/move-package" }
# move-stdlib = { path = "../../../diem/language/move-stdlib" }
# move-vm-runtime = { path = "../../../diem/language/move-vm/runtime" }
# move-vm-types = { path = "../../../diem/language/move-vm/types" }

move-binary-format = { git = "https://github.com/diem/diem", rev="661a2d1367a64a02027e4ed8f4b18f0a37cfaa17" }
move-core-types = { git = "https://github.com/diem/diem", rev="661a2d1367a64a02027e4ed8f4b18f0a37cfaa17" }
move-lang = { git = "https://github.com/diem/diem", rev="661a2d1367a64a02027e4ed8f4b18f0a37cfaa17" }
move-package = { git = "https://github.com/diem/diem", rev="661a2d1367a64a02027e4ed8f4b18f0a37cfaa17" }
move-stdlib = { git = "https://github.com/diem/diem", rev="661a2d1367a64a02027e4ed8f4b18f0a37cfaa17" }
move-vm-runtime = { git = "https://github.com/diem/diem", rev="661a2d1367a64a02027e4ed8f4b18f0a37cfaa17" }
move-vm-types = { git = "https://github.com/diem/diem", rev="661a2d1367a64a02027e4ed8f4b18f0a37cfaa17" }
