[package]
name = "FastX"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/diem/diem.git", subdir="language/move-stdlib", rev = "5572eae5e35407f10316b473f95cb155a5e8d40b" }

[addresses]
Std = "0x1"
FastX = "0x2"
Examples = "0x2"

[dev-addresses]
Std = "0x1"
FastX = "0x2"
Examples = "0x2"
