---
name: Simulator Tests

concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    if: always()  # always notify
    steps:
      - name: Post to slack
        uses: slackapi/slack-github-action@v1.24.0  # pin@v1.21.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: simtest-nightly
          payload: |-
            {
              "text": "TEST",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "TEST SLACK MESSAGE"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<@sui-core> this is a test, ignore this message"
                  }
                }
              ]
            }
